import { properties, mxn } from './data.js';
import { isConnected, requestAccess, signTransaction } from '@stellar/freighter-api';
import * as StellarSdk from '@stellar/stellar-sdk';
import './style.css';

const app = document.querySelector('#app');
const config = {
  contract: import.meta.env.VITE_CONTRACT_ID || '',
  rpc: import.meta.env.VITE_STELLAR_RPC || 'https://soroban-testnet.stellar.org',
  network: StellarSdk.Networks.TESTNET,
  api: import.meta.env.VITE_API_URL || 'http://localhost:8787'
};
let selected = properties[0], wallet = '', analysis = null, busy = false, txResult = '';
const status = id => localStorage.getItem('traccia-demo-'+id) || 'Disponible';
function render(){
  app.innerHTML = `<header class="top"><a class="brand" href="#" aria-label="Traccia inicio"><span class="brandmark">T</span><span>traccia<small>STELLAR TESTNET · DEMO</small></span></a><div class="topright"><span class="network"><i></i> Red de prueba</span><button id="wallet" class="wallet">${wallet ? wallet.slice(0,5)+'…'+wallet.slice(-4) : 'Conectar Freighter'}</button></div></header>
  <main><section class="intro"><div><span class="eyebrow">FRACCIONAMIENTO PILOTO / 05 PROPIEDADES</span><h1>Cada propiedad tiene<br><em>una historia verificable.</em></h1><p>Explora inmuebles ficticios, revisa cómo se calculó su valoración y prueba una reserva en Stellar.</p></div><div class="intro-stat"><span>ÍNDICE DE MERCADO</span><strong>84<span>/100</span></strong><small>Promedio ilustrativo de la demo</small></div></section>
  <section class="workspace" aria-label="Explorador de propiedades"><div class="left"><div class="section-head"><div><span class="eyebrow">01 / EXPLORAR</span><h2>Plano del fraccionamiento</h2></div><span class="count">5 lotes</span></div><div class="map"><div class="road road-h">CALLE CENTRAL</div><div class="road road-v"></div>${properties.map(p=>`<button class="plot ${selected.id===p.id?'active':''} ${p.tone}" style="left:${p.x}%;top:${p.y}%" data-id="${p.id}" aria-label="Seleccionar ${p.name}"><span class="plot-number">${p.id}</span><strong>${p.name.replace('Casa ','')}</strong><small>${p.area} m² · ${status(p.id)}</small></button>`).join('')}</div><div class="map-footer"><span><i class="legend available"></i> Disponible</span><span><i class="legend current"></i> Seleccionada</span><span>Plano conceptual · sin ubicación real</span></div></div>
  <aside class="detail"><div class="detail-top"><span class="eyebrow">02 / DETALLE DE PROPIEDAD</span><span class="badge">${status(selected.id)}</span></div><div class="house-art ${selected.tone}"><span class="art-sun"></span><span class="art-house"><span></span><span></span></span><span class="art-caption">LOTE ${selected.lot} · TRACCIA RESIDENCES</span></div><div class="detail-body"><div class="title-row"><div><h2>${selected.name}</h2><p>${selected.description}</p></div><span class="id">#${selected.id}</span></div><div class="metrics"><div><small>Precio de referencia</small><strong>${mxn(selected.price)}</strong></div><div><small>Construcción</small><strong>${selected.area} m²</strong></div><div><small>Terreno</small><strong>${selected.land} m²</strong></div></div><div class="score"><div><small>AI MARKET SCORE</small><strong>${analysis?.propertyId===selected.id ? analysis.score : selected.score}<span>/100</span></strong></div><div class="score-right"><span>↗ +${selected.change}%</span><small>Variación ilustrativa</small></div></div><div class="actions"><button id="analyze" class="secondary" ${busy?'disabled':''}>${busy?'Analizando…':'Analizar con IA'}</button><button id="reserve" class="primary" ${busy?'disabled':''}>Reservar en Testnet <span>↗</span></button></div><p class="disclaimer">Demo con inmuebles ficticios. La reserva digital no transfiere derechos inmobiliarios.</p></div></aside></section>
  <section class="trace"><div><span class="eyebrow">03 / TRAZABILIDAD</span><h2>Del dato a la transacción</h2></div><div class="steps"><span>01 <b>Fuentes verificables</b></span><span>02 <b>Valoración de IA</b></span><span>03 <b>Hash y oráculo</b></span><span>04 <b>Contrato Soroban</b></span></div></section></main><div id="overlay"></div>`;
  document.querySelectorAll('.plot').forEach(el=>el.onclick=()=>{ selected=properties.find(p=>p.id===el.dataset.id); analysis=null; txResult=''; render(); });
  document.querySelector('#wallet').onclick=connect;
  document.querySelector('#analyze').onclick=analyze;
  document.querySelector('#reserve').onclick=reserve;
  if(analysis?.propertyId===selected.id) showAnalysis();
  if(txResult) showModal(txResult);
}
function showModal(content){const node=document.querySelector('#overlay'); node.innerHTML=`<div class="veil"><section class="modal" role="dialog" aria-modal="true"><button class="close" aria-label="Cerrar">×</button>${content}</section></div>`; node.querySelector('.close').onclick=()=>{node.innerHTML='';txResult=''};node.querySelector('.veil').onclick=e=>{if(e.target.classList.contains('veil')){node.innerHTML='';txResult=''}};}
function showAnalysis(){let a=analysis; showModal(`<span class="eyebrow">VALORACIÓN / ${a.mode==='live'?'GEMINI':'DATOS ILUSTRATIVOS'}</span><h2>${selected.name}</h2><p>${a.summary}</p><div class="analysis-grid"><div><small>Valor estimado</small><strong>${mxn(a.valuationMxn)}</strong></div><div><small>Market score</small><strong>${a.score}/100</strong></div><div><small>Confianza</small><strong>${a.confidence}%</strong></div></div><p class="hash">SHA-256 · ${a.hash}</p><h3>Fuentes</h3><ul>${a.sources.map(s=>`<li>${s.url ? `<a href="${escapeHtml(s.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(s.title)}</a>` : escapeHtml(s.title)}</li>`).join('')}</ul><small class="muted">Fecha: ${new Date(a.timestamp).toLocaleString('es-MX')}. La valoración es informativa y no constituye avalúo.</small>`);}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function connect(){try{const available=await isConnected();if(!available.isConnected) throw Error('Instala y desbloquea Freighter para continuar.');const result=await requestAccess();if(result.error) throw Error(result.error);wallet=result.address;render();}catch(e){showModal(`<h2>Conectar wallet</h2><p>${escapeHtml(e.message)}</p>`);}}
async function analyze(){busy=true;render();try{const res=await fetch(`${config.api}/api/analyze/${selected.id}`);const data=await res.json();if(!res.ok) throw Error(data.error||'No se pudo analizar.');analysis=data;render();}catch(e){busy=false;render();showModal(`<h2>Análisis no disponible</h2><p>${escapeHtml(e.message)} Inicia el servidor y configura GEMINI_API_KEY para un análisis real.</p>`);}finally{busy=false;document.querySelector('#analyze').disabled=false;document.querySelector('#reserve').disabled=false;}}
async function reserve(){if(!wallet){await connect();if(!wallet)return;}if(!config.contract){showModal('<h2>Contrato pendiente de configuración</h2><p>Despliega el contrato en Testnet y configura VITE_CONTRACT_ID. Consulta README.md para completar la reserva real.</p>');return;}busy=true;render();try{const rpc=new StellarSdk.rpc.Server(config.rpc);const account=await rpc.getAccount(wallet);const contract=new StellarSdk.Contract(config.contract);const tx=new StellarSdk.TransactionBuilder(account,{fee:'100000',networkPassphrase:config.network}).addOperation(contract.call('reserve',StellarSdk.nativeToScVal(selected.id,{type:'string'}),StellarSdk.Address.fromString(wallet).toScVal())).setTimeout(60).build();const prepared=await rpc.prepareTransaction(tx);const signed=await signTransaction(prepared.toXDR(),{networkPassphrase:config.network,address:wallet});if(signed.error)throw Error(signed.error);const sent=await rpc.sendTransaction(StellarSdk.TransactionBuilder.fromXDR(signed.signedTxXdr,config.network));if(sent.status==='ERROR')throw Error('La red rechazó la transacción.');let receipt;for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,1500));receipt=await rpc.getTransaction(sent.hash);if(receipt.status!=='NOT_FOUND')break;}if(receipt?.status!=='SUCCESS')throw Error('La operación se envió, pero aún no se confirmó. Hash: '+sent.hash);localStorage.setItem('traccia-demo-'+selected.id,'Reservada');txResult=`<span class="eyebrow">RESERVA CONFIRMADA</span><h2>${selected.name}</h2><p>La reserva digital se registró en Stellar Testnet.</p><p class="hash">TX · ${sent.hash}</p><a target="_blank" rel="noopener noreferrer" href="https://stellar.expert/explorer/testnet/tx/${encodeURIComponent(sent.hash)}">Ver transacción ↗</a>`;render();}catch(e){showModal(`<h2>No se completó la reserva</h2><p>${escapeHtml(e.message)}</p>`);}finally{busy=false;}}
render();
